### ISSUE TITLE
update README.md

### ISSUE THREAD

**Issue by nofatigue** [mrhappyasthma/runelite-profit-tracker#4]
:)

**Comment by nofatigue** [comment]
Actually I don't know if changing README.md is the solution, but the repo link in runelite plugin web points to my repo and there's no reference for yours. IDK

**Comment by mrhappyasthma** [comment]
I believe I fixed this in https://github.com/mrhappyasthma/runelite-profit-tracker/commit/5f3cf1082fab8e9eb0828c2195c3426d3553d650. I just need to update the RuneLite pluginhub repo to point to this new commit.

I was planning to make some other code changes and then just update the plugin hub once, but it took longer than I thought haha.

I can send out a pull request for that and also make README changes once I'm off work. :)

And thanks again for making the plugin in the first place. I love it :D
